env:
  es6: true
  node: true
extends: 'eslint:recommended'
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 2018
  sourceType: module
rules: {
  "bitwise": true,
  "eqeqeq": 0,
  "es3": true,
  "forin": true,
  "freeze": true,
  "immed": true,
  "latedef": "nofucn",
  "noarg": true,
  "noempty": true,
  "nonbsp": true,
  "nonew": true,
  "undef": true,
  "unused": true,
  "no-console": 0,
  "browser": true,
  "node": true,
  "no-undef": 0,
  "globals": {
    "modules": false
  },

  "expr": true,
  "sub": true
}
