env:
  es6: 1
  node: 1
extends: 'eslint:recommended'
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 2018
  sourceType: module
rules: {
  no-undef: 0,
  no-prototype-builtins: 0
}
